version: '3'
services:
  sonarqubeweb:
    image: sonarqube:latest
    hostname: sonar.pulse
    container_name: sonarqube-cicd
    restart: always
    ports:
      - "9082:9000"
      - "80:9000"
    environment:
      - "SONAR_JDBC_USERNAME=sonarqube"
      - "SONAR_JDBC_PASSWORD=sonarqube"
    volumes:
      - ./sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_logs:/opt/sonarqube/logs
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - /etc/hosts:/etc/hosts:ro
