version: '3'
services:
  sonarqubeweb:
    labels:
          - "docker.group=sonarkubeweb"
    image: sonarqube:latest
    hostname: sonar.pulse
    container_name: sonarqube-cicd
    restart: always
    ports:
      - "9082:9000"
      - "80:9000"
    environment:
      - "SONAR_JDBC_USERNAME=sonarqube"
      - "SONAR_JDBC_PASSWORD=sonarqube"
    volumes:
      - ./sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_logs:/opt/sonarqube/logs
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - /etc/hosts:/etc/hosts:ro

  netdata:
    labels:
          - "docker.group=sonarkube_netdata"
    image: netdata/netdata
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '19999:19999'

  netdata-grabber:
    labels:
          - "docker.group=netdata-grabber"
    image: terorie/netdata-influx
    environment:
      - NI_INFLUX_ADDR=http://172.17.177.50:8086
      - NI_INFLUX_DB=sonarkube_netdata
      - NI_NETDATA_API=http://172.17.177.44:19999/api
      - NI_HOST_TAG=sonarkube-main
      - NI_CHARTS=system.cpu system.net system.pgpgio
    restart: always

volumes:
  influxdb-storage:
